### ISSUE TITLE
Sonarqube 6.7.3 - org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: plugins directory [/opt/sonarqube/elasticsearch/plugins] not found

### ISSUE THREAD

**Issue by jdoshi1** [SonarSource/docker-sonarqube#176]
sonarqube = v6.7.3
running as non-root user `sonarqube`

Elasticsearch is looking for a /opt/sonarqube/elasticsearch/plugins directory and failing if not found.

Everything works on v6.7.2

Logs:
**docker-compose log of sonarqube service**:
```
sonarqube_1     | 2018.05.11 18:23:22 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
sonarqube_1     | 2018.05.11 18:23:22 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
sonarqube_1     | 2018.05.11 18:23:22 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonarqube/temp/conf/es
sonarqube_1     | 2018.05.11 18:23:22 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
sonarqube_1     | 2018.05.11 18:23:25 INFO  app[][o.e.p.PluginsService] no modules loaded
sonarqube_1     | 2018.05.11 18:23:25 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
sonarqube_1     | 2018.05.11 18:23:25 DEBUG app[][o.e.t.ThreadPool] created thread pool: name [force_merge], size [1], queue size [unbounded]
sonarqube_1     | 2018.05.11 18:23:25 DEBUG app[][o.e.t.ThreadPool] created thread pool: name [fetch_shard_started], core [1], max [24], keep alive [5m]
sonarqube_1     | 2018.05.11 18:23:25 DEBUG app[][o.e.t.ThreadPool] created thread pool: name [listener], size [6], queue size [unbounded]
sonarqube_1     | 2018.05.11 18:23:25 DEBUG app[][o.e.t.ThreadPool] created thread pool: name [index], size [12], queue size [200]
sonarqube_1     | 2018.05.11 18:23:25 DEBUG app[][o.e.t.ThreadPool] created thread pool: name [refresh], core [1], max [6], keep alive [5m]
sonarqube_1     | 2018.05.11 18:23:25 DEBUG app[][o.e.t.ThreadPool] created thread pool: name [generic], core [4], max [128], keep alive [30s]
sonarqube_1     | 2018.05.11 18:23:25 DEBUG app[][o.e.t.ThreadPool] created thread pool: name [warmer], core [1], max [5], keep alive [5m]
sonarqube_1     | 2018.05.11 18:23:25 DEBUG app[][o.e.t.ThreadPool] created thread pool: name [search], size [19], queue size [1k]
sonarqube_1     | 2018.05.11 18:23:25 DEBUG app[][o.e.t.ThreadPool] created thread pool: name [flush], core [1], max [5], keep alive [5m]
sonarqube_1     | 2018.05.11 18:23:25 DEBUG app[][o.e.t.ThreadPool] created thread pool: name [fetch_shard_store], core [1], max [24], keep alive [5m]
sonarqube_1     | 2018.05.11 18:23:25 DEBUG app[][o.e.t.ThreadPool] created thread pool: name [management], core [1], max [5], keep alive [5m]
sonarqube_1     | 2018.05.11 18:23:25 DEBUG app[][o.e.t.ThreadPool] created thread pool: name [get], size [12], queue size [1k]
sonarqube_1     | 2018.05.11 18:23:25 DEBUG app[][o.e.t.ThreadPool] created thread pool: name [bulk], size [12], queue size [200]
sonarqube_1     | 2018.05.11 18:23:25 DEBUG app[][o.e.t.ThreadPool] created thread pool: name [snapshot], core [1], max [5], keep alive [5m]
sonarqube_1     | 2018.05.11 18:23:25 DEBUG app[][o.e.c.n.IfConfig] configuration:
sonarqube_1     | 
sonarqube_1     | lo
sonarqube_1     |         inet 127.0.0.1 netmask:255.0.0.0 scope:host
sonarqube_1     |         inet6 ::1 prefixlen:128 scope:host
sonarqube_1     |         UP LOOPBACK mtu:65536 index:1
sonarqube_1     | 
sonarqube_1     | eth1
sonarqube_1     |         inet 172.23.0.2 netmask:255.255.0.0 broadcast:0.0.0.0 scope:site
sonarqube_1     |         inet6 fe80::42:acff:fe17:2 prefixlen:64 scope:link
sonarqube_1     |         hardware 02:42:AC:17:00:02
sonarqube_1     |         UP MULTICAST mtu:1500 index:1262
sonarqube_1     | 
sonarqube_1     | eth0
sonarqube_1     |         inet 172.24.0.3 netmask:255.255.0.0 broadcast:0.0.0.0 scope:site
sonarqube_1     |         inet6 fe80::42:acff:fe18:3 prefixlen:64 scope:link
sonarqube_1     |         hardware 02:42:AC:18:00:03
sonarqube_1     |         UP MULTICAST mtu:1500 index:1266
sonarqube_1     | 
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.i.i.Stopwatch] Module execution: 48ms
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.i.i.Stopwatch] TypeListeners creation: 1ms
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.i.i.Stopwatch] Scopes creation: 1ms
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.i.i.Stopwatch] Converters creation: 0ms
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.i.i.Stopwatch] Binding creation: 3ms
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.i.i.Stopwatch] Private environment creation: 0ms
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.i.i.Stopwatch] Injector construction: 0ms
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.i.i.Stopwatch] Binding initialization: 3ms
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.i.i.Stopwatch] Binding indexing: 0ms
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.i.i.Stopwatch] Collecting injection requests: 0ms
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.i.i.Stopwatch] Binding validation: 0ms
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.i.i.Stopwatch] Static validation: 0ms
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.i.i.Stopwatch] Instance member validation: 1ms
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.i.i.Stopwatch] Provider verification: 0ms
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.i.i.Stopwatch] Static member injection: 0ms
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.i.i.Stopwatch] Instance injection: 0ms
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.i.i.Stopwatch] Preloading singletons: 1ms
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.t.TransportClientNodesService] node_sampler_interval[5s]
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.c.MultithreadEventLoopGroup] -Dio.netty.eventLoopThreads: 24
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.i.PlatformDependent0] -Dio.netty.noUnsafe: false
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.i.PlatformDependent0] Java version: 8
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.i.PlatformDependent0] sun.misc.Unsafe.theUnsafe: available
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.i.PlatformDependent0] sun.misc.Unsafe.copyMemory: available
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.i.PlatformDependent0] java.nio.Buffer.address: available
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.i.PlatformDependent0] direct buffer constructor: available
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.i.PlatformDependent0] java.nio.Bits.unaligned: available, true
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.i.PlatformDependent0] jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.i.PlatformDependent0] java.nio.DirectByteBuffer.<init>(long, int): available
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.i.PlatformDependent] sun.misc.Unsafe: available
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.i.PlatformDependent] -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.i.PlatformDependent] -Dio.netty.bitMode: 64 (sun.arch.data.model)
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.i.PlatformDependent] -Dio.netty.noPreferDirect: false
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.i.PlatformDependent] -Dio.netty.maxDirectMemory: 7481065472 bytes
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.i.PlatformDependent] -Dio.netty.uninitializedArrayAllocationThreshold: -1
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.i.CleanerJava6] java.nio.ByteBuffer.cleaner(): available
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.c.n.NioEventLoop] -Dio.netty.noKeySetOptimization: false
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.c.n.NioEventLoop] -Dio.netty.selectorAutoRebuildThreshold: 512
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.i.PlatformDependent] org.jctools-core.MpscChunkedArrayQueue: available
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.t.TransportClientNodesService] adding address [{#transport#-1}{3suspJCmSAawv3KZq_MZyA}{127.0.0.1}{127.0.0.1:9001}]
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.c.DefaultChannelId] -Dio.netty.processId: 1 (auto-detected)
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.netty.util.NetUtil] -Djava.net.preferIPv4Stack: false
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.netty.util.NetUtil] -Djava.net.preferIPv6Addresses: false
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.netty.util.NetUtil] Loopback interface: lo (lo, 0:0:0:0:0:0:0:1%lo)
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.netty.util.NetUtil] /proc/sys/net/core/somaxconn: 128
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.c.DefaultChannelId] -Dio.netty.machineId: 02:42:ac:ff:fe:17:00:02 (auto-detected)
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.ResourceLeakDetector] -Dio.netty.leakDetection.level: simple
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.u.ResourceLeakDetector] -Dio.netty.leakDetection.maxRecords: 4
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.b.PooledByteBufAllocator] -Dio.netty.allocator.numHeapArenas: 24
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.b.PooledByteBufAllocator] -Dio.netty.allocator.numDirectArenas: 24
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.b.PooledByteBufAllocator] -Dio.netty.allocator.pageSize: 8192
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.b.PooledByteBufAllocator] -Dio.netty.allocator.maxOrder: 11
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.b.PooledByteBufAllocator] -Dio.netty.allocator.chunkSize: 16777216
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.b.PooledByteBufAllocator] -Dio.netty.allocator.tinyCacheSize: 512
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.b.PooledByteBufAllocator] -Dio.netty.allocator.smallCacheSize: 256
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.b.PooledByteBufAllocator] -Dio.netty.allocator.normalCacheSize: 64
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.b.PooledByteBufAllocator] -Dio.netty.allocator.maxCachedBufferCapacity: 32768
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.b.PooledByteBufAllocator] -Dio.netty.allocator.cacheTrimInterval: 8192
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.b.PooledByteBufAllocator] -Dio.netty.allocator.useCacheForAllThreads: true
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.b.ByteBufUtil] -Dio.netty.allocator.type: pooled
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.b.ByteBufUtil] -Dio.netty.threadLocalDirectBufferSize: 65536
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][i.n.b.ByteBufUtil] -Dio.netty.maxThreadLocalCharBufferSize: 16384
sonarqube_1     | 2018.05.11 18:23:29 DEBUG app[][o.e.c.t.TransportClientNodesService] failed to connect to node [{#transport#-1}{3suspJCmSAawv3KZq_MZyA}{127.0.0.1}{127.0.0.1:9001}], ignoring...
sonarqube_1     | org.elasticsearch.transport.ConnectTransportException: [][127.0.0.1:9001] connect_timeout[30s]
sonarqube_1     | 	at org.elasticsearch.transport.netty4.Netty4Transport.connectToChannels(Netty4Transport.java:362)
sonarqube_1     | 	at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:570)
sonarqube_1     | 	at org.elasticsearch.transport.TcpTransport.openConnection(TcpTransport.java:117)
sonarqube_1     | 	at org.elasticsearch.transport.TransportService.openConnection(TransportService.java:351)
sonarqube_1     | 	at org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler.doSample(TransportClientNodesService.java:407)
sonarqube_1     | 	at org.elasticsearch.client.transport.TransportClientNodesService$NodeSampler.sample(TransportClientNodesService.java:357)
sonarqube_1     | 	at org.elasticsearch.client.transport.TransportClientNodesService.addTransportAddresses(TransportClientNodesService.java:198)
sonarqube_1     | 	at org.elasticsearch.client.transport.TransportClient.addTransportAddress(TransportClient.java:319)
sonarqube_1     | 	at org.sonar.application.process.EsProcessMonitor.addHostToClient(EsProcessMonitor.java:186)
sonarqube_1     | 	at org.sonar.application.process.EsProcessMonitor.buildTransportClient(EsProcessMonitor.java:177)
sonarqube_1     | 	at org.sonar.application.process.EsProcessMonitor.getTransportClient(EsProcessMonitor.java:160)
sonarqube_1     | 	at org.sonar.application.process.EsProcessMonitor.checkStatus(EsProcessMonitor.java:134)
sonarqube_1     | 	at org.sonar.application.process.EsProcessMonitor.checkOperational(EsProcessMonitor.java:93)
sonarqube_1     | 	at org.sonar.application.process.EsProcessMonitor.isOperational(EsProcessMonitor.java:78)
sonarqube_1     | 	at org.sonar.application.process.SQProcess.refreshState(SQProcess.java:162)
sonarqube_1     | 	at org.sonar.application.process.SQProcess$EventWatcher.run(SQProcess.java:221)
sonarqube_1     | Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: /127.0.0.1:9001
sonarqube_1     | 	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
sonarqube_1     | 	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
sonarqube_1     | 	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:352)
sonarqube_1     | 	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
sonarqube_1     | 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:632)
sonarqube_1     | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
sonarqube_1     | 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
sonarqube_1     | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
sonarqube_1     | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
sonarqube_1     | 	at java.lang.Thread.run(Thread.java:748)
sonarqube_1     | Caused by: java.net.ConnectException: Connection refused
```

**Elasticsearch logs**:

`cat /opt/sonarqube/logs/es.log`:

```
2018.05.11 18:24:03 ERROR es[][o.e.b.Bootstrap] Exception
java.lang.IllegalStateException: plugins directory [/opt/sonarqube/elasticsearch/plugins] not found
	at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:68) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:168) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) [elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) [elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) [elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) [elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) [elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) [elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) [elasticsearch-5.6.3.jar:5.6.3]
2018.05.11 18:24:03 WARN  es[][o.e.b.ElasticsearchUncaughtExceptionHandler] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: plugins directory [/opt/sonarqube/elasticsearch/plugins] not found
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) ~[elasticsearch-5.6.3.jar:5.6.3]
Caused by: java.lang.IllegalStateException: plugins directory [/opt/sonarqube/elasticsearch/plugins] not found
	at org.elasticsearch.bootstrap.Spawner.spawnNativePluginControllers(Spawner.java:68) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:168) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.3.jar:5.6.3]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.3.jar:5.6.3]
	... 6 more
```

**Comment by janos-ss** [comment]
We've just released official images of SonarQube Community Edition 7.4 and 6.7.6, available on the [hub](https://hub.docker.com/_/sonarqube/). Can you please try with those?

**Comment by digitalson** [comment]
@janos-ss I am on a fresh install of 6.7.6 LTS and am still getting the same error as posted above.

**Comment by simonbrandhof** [comment]
Please re-open this issue if the new versions don't fix the error.
